### ISSUE TITLE
Update description of the CLYH ontology

### ISSUE THREAD

**Issue by L-Leclere** [EBISPOT/clyh_ontology#5]
Request for updating the description of the clyh ontology on the EMBL-EBI ontology website.

Current description: 
"The Cytia hemisphaerica Development and Anatomy Ontology (CLYH) is to describe the anatomy, development and life cycle stages - planula, polyp, medusa/jellyfish - of the hydrozoan species, Clytia hemiphaerica, member of the phylum Cnidaria."

New version:
"Anatomy, development and life cycle stages - planula, polyp, medusa/jellyfish - of the cnidarian hydrozoan species, Clytia hemiphaerica"

**Comment by matentzn** [comment]
@L-Leclere 

Please follow these instructions:

1) Go to https://github.com/EBISPOT/clyh_ontology/blob/master/src/ontology/clyh-edit.owl
2) Hit the edit button (a small symbol of a pencil)
3) Change the description 

```
Annotation(<http://purl.org/dc/elements/1.1/description> "The Cytia hemisphaerica Development and Anatomy Ontology (CLYH) is to describe the anatomy, development and life cycle stages - planula, polyp, medusa/jellyfish - of the hydrozoan species, Clytia hemiphaerica, member of the phylum Cnidaria."^^xsd:string)
```

By updating it to whatever you wish.

4) Scroll down, select `Create a new branch for this commit and start a pull request`
5) Click `Commit changes` / `Propose file change`
6) Click in the section `Leave a comment` write @matentzn 
7) Click `Create pull request`

Done. I will review your work, and merge it into master.

**Comment by matentzn** [comment]
Closed by https://github.com/EBISPOT/clyh_ontology/pull/6
